#### Tables

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datascience import Table
plt.style.use('fivethirtyeight')

# df_cones = pd.read_csv('data/cones.csv')
# df_nba = pd.read_csv('data/nba_salaries.csv')

tb_cones = Table.read_table('data/cones.csv')
tb_nba = Table.read_table('data/nba_salaries.csv')

In [39]:
tb_nba.show(10)

In [ ]:
tb_nba.where

In [30]:
tb_cones.drop('Price')

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [36]:
tb_cones = tb_cones.drop('Price')
tb_cones

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink